# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html


# To use this, copy this to a new file and remove the period from the file name
# Replace the REPLACEME in this file with something like bensdevenv
# When using sam build or sam sync add --config-file samconfig.dev.toml
# Do not commit this to version control, it's only for your testing

version = 0.1

[default]
[default.global.parameters]
stack_name = "REPLACEME"

[default.build.parameters]
cached = true
parallel = true
beta_features = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = false
resolve_s3 = true
s3_prefix = "bookboost"

# !!! You can set your region and credentials profile here !!!
region = "us-east-1"
profile = "group49"

image_repositories = []
disable_rollback = false

# !!! Override the parameters here for your own dev stack !!!
parameter_overrides = [
  "Env=dev",
  "BaseDomain=REPLACEME.bookboost.app",
  "HostedZoneId=Z07509833Q0P5V3TCGCLC",
  "JwtIssuer=https://auth.bookboost.app/",
  "JwtAudience=https://a8sh3eh6pj.execute-api.us-east-2.amazonaws.com",
  "FilesBucketName=bookboost-REPLACEME-files"
]

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true
beta_features = true
# Currently these values have to exist in both sync and build to work for both
parameter_overrides = [
  "Env=dev",
  "BaseDomain=REPLACEME.bookboost.app",
  "HostedZoneId=Z07509833Q0P5V3TCGCLC",
  "JwtIssuer=https://auth.bookboost.app/",
  "JwtAudience=https://a8sh3eh6pj.execute-api.us-east-2.amazonaws.com",
  "FilesBucketName=bookboost-REPLACEME-files"
]

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"