AWSTemplateFormatVersion: 2010-09-09
Description: >-
  bookboost-lambdas-sam/audiobooks
Transform:
  - AWS::Serverless-2016-10-31
Parameters:
  SnsTopic:
    Type: String
  FQDN:
    Type: String
  ZoneId:
    Type: String
  JwtIssuer:
    Type: String
  JwtAudience:
    Type: String

Globals:
  Function:
    Timeout: 100
    Runtime: nodejs20.x
    CodeUri: .
    Environment:
      Variables:
        STRIPE_SECRET_KEY: '{{resolve:ssm:Prod.STRIPE_SECRET_KEY}}'
        STRIPE_ENDPOINT_SECRET: '{{resolve:ssm:Prod.STRIPE_ENDPOINT_SECRET}}'
        SUBSCRIPTIONS_TABLE: !Ref SubscriptionsTable
        SNS_TOPIC: !Ref SnsTopic
        NODE_OPTIONS: '--enable-source-maps'

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref FQDN
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref FQDN
          HostedZoneId: !Ref ZoneId
  CoreApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Auth:
        Authorizers:
          Auth0:
            IdentitySource: '$request.header.Authorization'
            JwtConfiguration:
              issuer: !Ref JwtIssuer
              audience:
                - !Ref JwtAudience
      StageName: prod
      Domain:
        DomainName: !Ref FQDN
        CertificateArn: !Ref Certificate
        Route53:
          HostedZoneId: !Ref ZoneId
      CorsConfiguration:
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
        AllowOrigins:
          - '*'
        AllowHeaders:
          - '*'
  WebookFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - Statement:
            - Sid: SNSPublishMessagePolicy
              Effect: Allow
              Action:
                - sns:Publish
              Resource: !Ref SnsTopic
        - DynamoDBCrudPolicy:
            TableName: !Ref SubscriptionsTable
      Handler: webhook.handler
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref CoreApi
            Path: /webhook
            Method: POST
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: 'es2020'
        Sourcemap: true
        EntryPoints:
          - webhook.ts
  CreatePortalSessionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: api.createPortalSession
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SubscriptionsTable
      Events:
        Api:
          Type: HttpApi
          Properties:
            Auth:
              Authorizer: Auth0
            ApiId: !Ref CoreApi
            Path: /portal/session
            Method: POST
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: 'es2020'
        Sourcemap: true
        EntryPoints:
          - api.ts
  GetSubscriptionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: api.getSubscription
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SubscriptionsTable
      Events:
        Api:
          Type: HttpApi
          Properties:
            Auth:
              Authorizer: Auth0
            ApiId: !Ref CoreApi
            Path: /subscription
            Method: GET
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: 'es2020'
        Sourcemap: true
        EntryPoints:
          - api.ts

  SubscriptionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
